# Generated by Django 5.1.4 on 2024-12-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('first_contact', models.CharField(max_length=20)),
                ('second_contact', models.CharField(max_length=20)),
                ('third_contact', models.CharField(max_length=20)),
                ('fourth_contact', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=30)),
            ],
        ),
    ]
