# Generated by Django 5.1.4 on 2024-12-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('indicator', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
            ],
        ),
    ]
