# Generated by Django 5.1.4 on 2024-12-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_method', models.CharField(max_length=20)),
                ('first', models.CharField(max_length=20)),
                ('second_method', models.CharField(max_length=30)),
                ('second', models.CharField(max_length=20)),
                ('third_method', models.CharField(max_length=20)),
                ('third', models.CharField(max_length=20)),
                ('fourth_method', models.CharField(max_length=20)),
                ('fourth', models.CharField(max_length=20)),
            ],
        ),
    ]
