# Generated by Django 5.1.4 on 2024-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_middlefirst'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('month', models.CharField(max_length=250)),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
    ]
