# Generated by Django 5.1.4 on 2024-12-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=250)),
                ('month', models.CharField(max_length=250)),
                ('day', models.IntegerField()),
                ('head', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('hours', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=50)),
                ('share', models.CharField(max_length=250)),
                ('last', models.CharField(max_length=250)),
            ],
        ),
    ]
