# Generated by Django 5.1.4 on 2024-12-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_usercontact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
