# Generated by Django 5.1.4 on 2024-12-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_fact_last_alter_about_text_alter_about_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middlefirst',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
