# Generated by Django 5.1.4 on 2024-12-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_middlefirst_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middlesecond',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='middlesecond',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
