# Generated by Django 5.1.4 on 2024-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_middlesecond_text_alter_middlesecond_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
