# Generated by Django 5.1.4 on 2024-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_last_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
