# Generated by Django 5.1.4 on 2024-12-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_detail_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='hours',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='last',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='detail',
            name='share',
            field=models.CharField(max_length=30),
        ),
    ]
