# Generated by Django 5.1.4 on 2024-12-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_detail_hours_alter_detail_last_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='header',
            name='menu',
        ),
    ]
