# Generated by Django 5.1.4 on 2024-12-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_meetingcategory_meetingheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='heading',
        ),
    ]
