# Generated by Django 5.1.4 on 2024-12-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_meeting_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='photo',
            field=models.ImageField(default=1, upload_to='popular_post/'),
            preserve_default=False,
        ),
    ]
