# Generated by Django 5.1.4 on 2024-12-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_popular_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meeting_photos/'),
        ),
    ]
