# Generated by Django 5.1.4 on 2024-12-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_meeting_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='popular_photos/'),
        ),
    ]
