# Generated by Django 5.1.4 on 2025-01-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='first_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='second_text',
            field=models.CharField(max_length=50),
        ),
    ]
