# Generated by Django 5.1.4 on 2025-01-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_meeting_first_text_alter_meeting_second_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(max_length=50),
        ),
    ]
