# Generated by Django 5.1.4 on 2025-01-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_meeting_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='popular',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
