# Generated by Django 5.1.4 on 2025-01-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_popular_price_alter_popular_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='invitation',
            field=models.CharField(max_length=50),
        ),
    ]
