# Generated by Django 5.1.4 on 2025-02-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_meeting_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/meeting_photos/'),
        ),
        migrations.AlterField(
            model_name='popular',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/popular_photos/'),
        ),
    ]
